= 案例研究：完美数的分类问题

古希腊数学家Nicomachus发明了一种自然数的分类方法，任意一个自然数都唯一地被归类为过剩数（abundant）、完美数（perfect）或不足数（deficient）。一个完美数的真约数（即除了自身以外的所有正约数）之和，恰好等于它本身。例如6是一个完美数，因为它的约数是1、2、3，而6 = 1 + 2 + 3；28也是一个完美数，因为28 = 1 + 2 + 4 + 7 + 14。

TIP: 真约数和（aliquot sum），其定义就是除了数本身之外（一个数总是它本身的约数），其余正约数的和


== First Attempt: 命令式解法
include::ImpNumberClassifierSimple.java[lines=12..]

ImpNumberClassifierSimple 类维持了两个内部状态

* `number` 字段为一系列函数省下一个参数
* `cache` 通过一个 Map 结构来缓存每个数字的真约数和，以在后续针对同一个数字的调用中更快地返回结果（查表是速度与计算速度的差别）。

TIP: 内部状态在面向对象编程的世界里受到推崇的平常做法，因为封装被 OOP 语言视为一项优势。 状态的划分往往为一些工程实践提供了便利，比如单元你测试的时候我们容易注入各种取值。

== Second Attempt: 稍微向函数式靠拢的解法

include::NumberClassifier.java[lines=9..]

* 众多方法都必须加上 `number` 参数，因为没有可以存放它的内部状态
* 所有方法都带 `public static` 修饰，因为它们都是**纯函数**，并因此可以在其他领域使用
* 选取尽可能宽泛的参数类型，可以增加函数重用的机会
* 重复执行分类操作的时候效率较低，因为没有缓存


NOTE: 纯函数即没有副作用的函数。

== Third Attempt: Java8 实现
include::NumberClassifierByLambda.java[lines=6..26]
* 代码比命令式解法以及不完全的函数式解法短得多也简单得多


针对无法使用 Java 高版本运行时，便需要使用一些开源框架（例如 Functional Java）来辅助函数式编程的实践。
