
== What

[quote,Java Documentation]
*SimpleDateFormat* is a concrete class for formatting and parsing dates in a locale-sensitive manner. It allows for formatting (date -> text), parsing (text -> date), and normalization. +
[...] +
Date formats are not synchronized. It is recommended to create separate format instances for each thread. If multiple threads access a format concurrently, it must be synchronized externally.



== When: SimpleDateFormat thread safety issue Example

[source,java]
----

include::{docdir}/../src/main/java/org/example/issues/issue0/SimpleDateFormatThreadUnsafeExample.java[lines=3..]

----



== Why

在 CalendarBuilder.establish() 方法中先后调用了 cal.clear() 与 cal.set()，也就是先清除 cal 对象中设置的值，再重新设置新的值。由于 Calendar 内部并没有线程安全机制，并且这两个操作也都不是原子性的，所以当多个线程同时操作一个 SimpleDateFormat 时就会引起 cal 的值混乱。类似地， *format() 方法也存在同样的问题*。

因此， SimpleDateFormat 类不是线程安全的根本原因是：*DateFormat 类中的 Calendar 对象被多线程共享，而 Calendar 对象本身不支持线程安全* 。


== How should I use SimpleDateFormat in a multithreaded environment?

* _Local Variable_ Create a new instance of `SimpleDateFormat` for each thread.
* _Synchronize Lock_ Synchronize concurrent access by multiple threads with a *synchronized* keyword or a *lock*.
** *synchronized* keywords
** *Lock* `java.util.concurrent.locks.Lock`
* _ThreadLocal_ Use `ThreadLocal` store a copy from instance of `SimpleDateFormat` for each thread.
* _Java8 New DateTime API_ DateTimeFormatter
* _Third Library_ joda-time

=== Local Variable(Not Recommended)

[source,java]
----

include::{docdir}/../src/main/java/org/example/issues/issue0/UseByLocalVariable.java[lines=3..]

----

这种方式在高并发下会创建大量的 SimpleDateFormat 类对象，浪费运行空间和消耗服务器的性能，因为 JVM 创建和销毁对象是要耗费性能的，所以，这种方式在**实际生产环境不太被推荐**。

=== Synchronized(Not Recommended)

[source,java]
----

include::{docdir}/../src/main/java/org/example/issues/issue0/UseBySynchronized.java[lines=3..]

----

由于在程序的执行过程中，为 SimpleDateFormat 类对象加上了 synchronized 锁，导致同一时刻只能有一个线程执行 parse(String) 方法。
此时，会影响程序的执行性能，*在要求高并发的生产环境下，此种方式也是不太推荐使用的*。


=== Lock(Not Recommended)

[source,java]
----

include::{docdir}/../src/main/java/org/example/issues/issue0/UseByLock.java[lines=3..]

----

首先，定义了一个Lock类型的全局静态变量作为加锁和释放锁的句柄。然后在simpleDateFormat.parse(String)代码之前通过lock.lock()加锁。此种方式同样会影响高并发场景下的性能，*不太建议在高并发的生产环境使用*。

=== ThreadLocal(Recommended)

[source,java]
----

include::{docdir}/../src/main/java/org/example/issues/issue0/UseByThreadLocal.java[lines=3..]

----

将每个线程使用的 SimpleDateFormat 副本保存在 ThreadLocal 中，各个线程在使用时互不干扰，从而解决了线程安全问题。
此种方式运行效率比较高，*推荐在高并发业务场景的生产环境使用*。



=== DateFormatter(Recommended)

Java 8 New Date/Time API.


[source,java]
----

include::{docdir}/../src/main/java/org/example/issues/issue0/UseByDateTimeFormatter.java[lines=3..]

----

== Conclusion

Don't use SimpleDateFormat.

应该避免使用 `Date` 和 `Calendar` 类，可以尝试使用 Java 8 DateTime 相关类如 OffsetDateTime，ZoneDateTime， LocalDateTime，LocalDate，LocalTime

== Reference

* https://www.callicoder.com/java-simpledateformat-thread-safety-issues/[Java's SimpleDateFormat is not thread-safe, Use carefully in multithreaded environments]
* https://zhuanlan.zhihu.com/p/395751163[SimpleDateFormat类为何不是线程安全的？（附六种解决方案）]

* https://www.cnblogs.com/three-fighter/p/14396208.html[Java synchronized 关键字详解]
* [LocalDate、LocalDateTime、DateTimeFormatter 是如何保证线程安全的？]
